version: '3.8'
services:
  # app:
  #   container_name: node
  #   build: .
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./:/app/
  #     - /node_modules
  postgres:
    container_name: db-postgres
    image: postgres:11.16-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pizza
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./postgres-db-data:/var/lib/postgresql/data
